# Generated by Django 4.2.1 on 2023-05-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
