# Generated by Django 4.2.1 on 2023-06-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='colaboradores')),
                ('descripcion', models.TextField()),
                ('enlace', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
